server:
  port: 9100

spring:
  application:
    name: springboot-mqtt

mqtt:
  url: tcp://gateway:1883
  timeout: 10

  sender:
    username: /iot_ownmq_host:iot_ownmq_user
    password: iot_ownmq_user
    #生产者连接服务器默认客户端id
    clientId: jx_iot_mqtt
    #默认的推送主题，实际可在调用接口时指定
    defaultTopic: /0s68kg0iimrkej/down
  receiver:
    username: /iot_ownmq_host:jb_0s68kg0iimrkej
    password: jb_0s68kg0iimrkej
    #消费者连接服务器默认客户端id
    clientId: ${random.value}
    defaultTopic: /0s68kg0iimrkej/up/#
